Develop3
kate99rina/Diplom_3 pull request #1
Opened 2023-03-19 18:38 UTC by kate99rina

Задание 3

2023-03-21 19:56 UTC, pavel-ulan requested changes
Хорошо, небольшие замечания по синтаксису.

2023-03-21 19:56 UTC, pavel-ulan commented on src/main/java/page_objects/LoginPage.java
> +    private By ENTER_FORM = By.xpath(".//h2[text()='Вход']");
**надо исправить**
не очень правильно использовать UPPER_CASE для простых полей, все же это наименование констант. Так что или сделай из них константы или исправь названия на camelCase.

2023-03-21 19:56 UTC, pavel-ulan commented on src/test/java/service/BaseTest.java
> +    }
**можно лучше**
зачем изобретать велосипед? Чем тебя стандартные ожидания не устроили?

2023-03-24 13:24 UTC, kate99rina commented on src/test/java/service/BaseTest.java
> +    }
подскажи, пожалуйста, что имеешь в виду под стандартным ожиданием?

2023-03-25 16:02 UTC, pavel-ulan approved these changes
Оке, не плохо

2023-03-25 16:02 UTC, pavel-ulan commented on src/test/java/service/BaseTest.java
> +    }
я имел в виду, зачем ты оборачиваешь ожидания в try catch, а после этого пробрасываешь исключение?
если ты хочешь, что бы было выброшено исключения используй неявные ожидания (они если не проходит проверка выбрасывают NoSuchElementException). 
а вообще, по хорошему, достаточно было оставить 
new WebDriverWait(driver, Duration.ofSeconds(5))
                    .until(ExpectedConditions.visibilityOfElementLocated(element));

2023-04-03 16:54 UTC, merged